# Generated by Django 5.1.6 on 2025-03-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='base_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_variation',
        ),
        migrations.AddField(
            model_name='product',
            name='variation',
            field=models.CharField(choices=[('1L', '1 Liter'), ('2L', '2 Liters'), ('1kg', '1 Kilogram'), ('2kg', '2 Kilograms')], default='1kg', max_length=10),
        ),
    ]
